version: "3.9"

services:
  backend:
    build: ./backend
    container_name: naksh-backend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_PORT=5000

  frontend:
    build: ./frontend
    container_name: naksh-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
